/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    query GetApiHealth {\n        isApiUp\n    }\n": typeof types.GetApiHealthDocument,
    "\n    mutation CreateAppImportJob($queueName: String!, $storageIndex: Int!) {\n        createAppImportJob(\n            queueName: $queueName,\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n": typeof types.CreateAppImportJobDocument,
    "\n    fragment AppAll on AndroidAppType {\n        absoluteStorePath\n        androidManifestDict\n        fileSizeBytes\n        filename\n        id\n        indexedDate\n        md5\n        originalFilename\n        packagename\n        partitionName\n        pk\n        relativeFirmwarePath\n        relativeStorePath\n        sha1\n        sha256\n        firmwareIdReference {\n            id\n        }\n        firmwareFileReference {\n            id\n        }\n    }\n": typeof types.AppAllFragmentDoc,
    "\n    query GetAppsByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    androidAppIdList {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.GetAppsByFirmwareObjectIdsDocument,
    "\n    query GetAppById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    androidAppIdList(id: $id) {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.GetAppByIdDocument,
    "\n    query GetScannerModuleNames {\n        scanner_module_name_list\n    }\n": typeof types.GetScannerModuleNamesDocument,
    "\n    mutation ScanApksByObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            objectIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n": typeof types.ScanApksByObjectIdsDocument,
    "\n    query GetAuthToken($password: String!, $username: String!) {\n        tokenAuth(password: $password, username: $username) {\n            payload\n        }\n    }\n": typeof types.GetAuthTokenDocument,
    "\n    mutation DeleteTokenCookie {\n        deleteTokenCookie {\n            deleted\n        }\n    }\n": typeof types.DeleteTokenCookieDocument,
    "\n    query GetCurrentUserId {\n        me {\n            id\n        }\n    }\n": typeof types.GetCurrentUserIdDocument,
    "\n    query GetCurrentUserEmailAndUsername {\n        me {\n            email\n            username\n        }\n    }\n": typeof types.GetCurrentUserEmailAndUsernameDocument,
    "\n    fragment FileAll on FirmwareFileType {\n        id\n        name\n        absoluteStorePath\n        fileSizeBytes\n        indexedDate\n        isDirectory\n        isOnDisk\n        isSymlink\n        md5\n        metaDict\n        parentDir\n        partitionName\n        relativePath\n        firmwareIdReference {\n            id\n        }\n        androidAppReference {\n            id\n        }\n    }\n": typeof types.FileAllFragmentDoc,
    "\n    query GetFilesByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    firmwareFileIdList {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.GetFilesByFirmwareObjectIdsDocument,
    "\n    query GetFileById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    firmwareFileIdList(id: $id) {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.GetFileByIdDocument,
    "\n    mutation CreateFirmwareExtractorJob($queueName: String!, $storageIndex: Int!) {\n        createFirmwareExtractorJob(\n            createFuzzyHashes: false\n            queueName: $queueName\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n": typeof types.CreateFirmwareExtractorJobDocument,
    "\n    fragment FirmwareAll on AndroidFirmwareType {\n        absoluteStorePath\n        aecsBuildFilePath\n        fileSizeBytes\n        filename\n        hasFileIndex\n        hasFuzzyHashIndex\n        id\n        indexedDate\n        md5\n        originalFilename\n        osVendor\n        partitionInfoDict\n        pk\n        relativeStorePath\n        sha1\n        sha256\n        tag\n        versionDetected\n    }\n": typeof types.FirmwareAllFragmentDoc,
    "\n    query GetFirmwaresByObjectIds(\n        $objectIds: [String!]\n        $first: Int\n        $after: String\n    ) {\n        android_firmware_connection(\n            objectIdList: $objectIds\n            first: $first\n            after: $after\n        ) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareAll\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n": typeof types.GetFirmwaresByObjectIdsDocument,
    "\n    fragment FirmwareRowImporterPage on AndroidFirmwareType {\n        id\n        indexedDate\n        originalFilename\n        osVendor\n        versionDetected\n    }\n": typeof types.FirmwareRowImporterPageFragmentDoc,
    "\n    query GetFirmwaresImporterPage($first: Int, $after: String) {\n        android_firmware_connection(first: $first, after: $after) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareRowImporterPage\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n": typeof types.GetFirmwaresImporterPageDocument,
    "\n    mutation ScanApksByFirmwareObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            firmwareIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n": typeof types.ScanApksByFirmwareObjectIdsDocument,
    "\n    mutation DeleteFirmwareByObjectId($objectIds: [String!]!) {\n        deleteAndroidFirmware(firmwareIdList: $objectIds) {\n            jobId\n        }\n    }\n": typeof types.DeleteFirmwareByObjectIdDocument,
    "\n    fragment BasicReportInfo on ApkScannerReportType {\n        id\n        reportDate\n        scannerName\n        scannerVersion\n        androidAppIdReference {\n            id\n            filename\n            firmwareIdReference {\n                id\n            }\n        }\n    }\n": typeof types.BasicReportInfoFragmentDoc,
    "\n    query GetReport($reportObjectId: String, $appObjectId: String, $scannerName: String) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId, android_app_id_reference: $appObjectId, scanner_name: $scannerName}) {\n            ...BasicReportInfo\n        }\n    }\n": typeof types.GetReportDocument,
    "\n    query GetScannerReport(\n        $reportObjectId: String\n        $wantAndroguard: Boolean! = false\n        $wantApkid: Boolean! = false\n        $wantApkleaks: Boolean! = false\n        $wantExodus: Boolean! = false\n    ) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId}) {\n            androidAppIdReference {\n                id\n                filename\n                firmwareIdReference {\n                    id\n                }\n                \n                androguardReport: androguardReportReference @include(if: $wantAndroguard) {\n                    ...AndroguardReport\n                }\n                apkidReport: apkidReportReference @include(if: $wantApkid) {\n                    ...ApkidReport\n                }\n                apkleaksReport: apkleaksReportReference @include(if: $wantApkleaks) {\n                    ...ApkleaksReport\n                }\n                exodusReport: exodusReportReference @include(if: $wantExodus) {\n                    ...ExodusReport\n                }\n            }\n        }\n    }\n": typeof types.GetScannerReportDocument,
    "\n    fragment AndroguardReport on AndroGuardReportType {\n        id\n        activities\n        androidVersionCode\n        androidVersionName\n        appName\n        dexNames\n        effectiveTargetVersion\n        fileNameList\n        intentFiltersDict\n        isAndroidtv\n        isLeanback\n        isMultidex\n        isSignedV1\n        isSignedV2\n        isSignedV3\n        isValidApk\n        isWearable\n        mainActivity\n        mainActivityList\n        manifestFeatures\n        manifestLibraries\n        manifestXml\n        maxSdkVersion\n        minSdkVersion\n        packagename\n        permissionDetails\n        permissions\n        permissionsDeclared\n        permissionsDeclaredDetails\n        permissionsImplied\n        permissionsRequestedThirdParty\n        providers\n        receivers\n        services\n        signatureNames\n        targetSdkVersion\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": typeof types.AndroguardReportFragmentDoc,
    "\n    fragment ApkidReport on ApkidReportType {\n        id\n        files\n        rulesSha256\n        reportFileJson {\n            data\n        }\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": typeof types.ApkidReportFragmentDoc,
    "\n    fragment ApkleaksReport on ApkleaksReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": typeof types.ApkleaksReportFragmentDoc,
    "\n    fragment ExodusReport on ExodusReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": typeof types.ExodusReportFragmentDoc,
    "\n    query GetRqJobList {\n        rq_job_list {\n            description\n            funcName\n            id\n            isFailed\n            isFinished\n            queueName\n            startedAt\n            status\n        }\n    }\n": typeof types.GetRqJobListDocument,
    "\n    query GetRqJobQueueNames {\n        rq_queue_name_list\n    }\n": typeof types.GetRqJobQueueNamesDocument,
};
const documents: Documents = {
    "\n    query GetApiHealth {\n        isApiUp\n    }\n": types.GetApiHealthDocument,
    "\n    mutation CreateAppImportJob($queueName: String!, $storageIndex: Int!) {\n        createAppImportJob(\n            queueName: $queueName,\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n": types.CreateAppImportJobDocument,
    "\n    fragment AppAll on AndroidAppType {\n        absoluteStorePath\n        androidManifestDict\n        fileSizeBytes\n        filename\n        id\n        indexedDate\n        md5\n        originalFilename\n        packagename\n        partitionName\n        pk\n        relativeFirmwarePath\n        relativeStorePath\n        sha1\n        sha256\n        firmwareIdReference {\n            id\n        }\n        firmwareFileReference {\n            id\n        }\n    }\n": types.AppAllFragmentDoc,
    "\n    query GetAppsByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    androidAppIdList {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.GetAppsByFirmwareObjectIdsDocument,
    "\n    query GetAppById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    androidAppIdList(id: $id) {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.GetAppByIdDocument,
    "\n    query GetScannerModuleNames {\n        scanner_module_name_list\n    }\n": types.GetScannerModuleNamesDocument,
    "\n    mutation ScanApksByObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            objectIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n": types.ScanApksByObjectIdsDocument,
    "\n    query GetAuthToken($password: String!, $username: String!) {\n        tokenAuth(password: $password, username: $username) {\n            payload\n        }\n    }\n": types.GetAuthTokenDocument,
    "\n    mutation DeleteTokenCookie {\n        deleteTokenCookie {\n            deleted\n        }\n    }\n": types.DeleteTokenCookieDocument,
    "\n    query GetCurrentUserId {\n        me {\n            id\n        }\n    }\n": types.GetCurrentUserIdDocument,
    "\n    query GetCurrentUserEmailAndUsername {\n        me {\n            email\n            username\n        }\n    }\n": types.GetCurrentUserEmailAndUsernameDocument,
    "\n    fragment FileAll on FirmwareFileType {\n        id\n        name\n        absoluteStorePath\n        fileSizeBytes\n        indexedDate\n        isDirectory\n        isOnDisk\n        isSymlink\n        md5\n        metaDict\n        parentDir\n        partitionName\n        relativePath\n        firmwareIdReference {\n            id\n        }\n        androidAppReference {\n            id\n        }\n    }\n": types.FileAllFragmentDoc,
    "\n    query GetFilesByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    firmwareFileIdList {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.GetFilesByFirmwareObjectIdsDocument,
    "\n    query GetFileById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    firmwareFileIdList(id: $id) {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.GetFileByIdDocument,
    "\n    mutation CreateFirmwareExtractorJob($queueName: String!, $storageIndex: Int!) {\n        createFirmwareExtractorJob(\n            createFuzzyHashes: false\n            queueName: $queueName\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n": types.CreateFirmwareExtractorJobDocument,
    "\n    fragment FirmwareAll on AndroidFirmwareType {\n        absoluteStorePath\n        aecsBuildFilePath\n        fileSizeBytes\n        filename\n        hasFileIndex\n        hasFuzzyHashIndex\n        id\n        indexedDate\n        md5\n        originalFilename\n        osVendor\n        partitionInfoDict\n        pk\n        relativeStorePath\n        sha1\n        sha256\n        tag\n        versionDetected\n    }\n": types.FirmwareAllFragmentDoc,
    "\n    query GetFirmwaresByObjectIds(\n        $objectIds: [String!]\n        $first: Int\n        $after: String\n    ) {\n        android_firmware_connection(\n            objectIdList: $objectIds\n            first: $first\n            after: $after\n        ) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareAll\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n": types.GetFirmwaresByObjectIdsDocument,
    "\n    fragment FirmwareRowImporterPage on AndroidFirmwareType {\n        id\n        indexedDate\n        originalFilename\n        osVendor\n        versionDetected\n    }\n": types.FirmwareRowImporterPageFragmentDoc,
    "\n    query GetFirmwaresImporterPage($first: Int, $after: String) {\n        android_firmware_connection(first: $first, after: $after) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareRowImporterPage\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n": types.GetFirmwaresImporterPageDocument,
    "\n    mutation ScanApksByFirmwareObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            firmwareIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n": types.ScanApksByFirmwareObjectIdsDocument,
    "\n    mutation DeleteFirmwareByObjectId($objectIds: [String!]!) {\n        deleteAndroidFirmware(firmwareIdList: $objectIds) {\n            jobId\n        }\n    }\n": types.DeleteFirmwareByObjectIdDocument,
    "\n    fragment BasicReportInfo on ApkScannerReportType {\n        id\n        reportDate\n        scannerName\n        scannerVersion\n        androidAppIdReference {\n            id\n            filename\n            firmwareIdReference {\n                id\n            }\n        }\n    }\n": types.BasicReportInfoFragmentDoc,
    "\n    query GetReport($reportObjectId: String, $appObjectId: String, $scannerName: String) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId, android_app_id_reference: $appObjectId, scanner_name: $scannerName}) {\n            ...BasicReportInfo\n        }\n    }\n": types.GetReportDocument,
    "\n    query GetScannerReport(\n        $reportObjectId: String\n        $wantAndroguard: Boolean! = false\n        $wantApkid: Boolean! = false\n        $wantApkleaks: Boolean! = false\n        $wantExodus: Boolean! = false\n    ) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId}) {\n            androidAppIdReference {\n                id\n                filename\n                firmwareIdReference {\n                    id\n                }\n                \n                androguardReport: androguardReportReference @include(if: $wantAndroguard) {\n                    ...AndroguardReport\n                }\n                apkidReport: apkidReportReference @include(if: $wantApkid) {\n                    ...ApkidReport\n                }\n                apkleaksReport: apkleaksReportReference @include(if: $wantApkleaks) {\n                    ...ApkleaksReport\n                }\n                exodusReport: exodusReportReference @include(if: $wantExodus) {\n                    ...ExodusReport\n                }\n            }\n        }\n    }\n": types.GetScannerReportDocument,
    "\n    fragment AndroguardReport on AndroGuardReportType {\n        id\n        activities\n        androidVersionCode\n        androidVersionName\n        appName\n        dexNames\n        effectiveTargetVersion\n        fileNameList\n        intentFiltersDict\n        isAndroidtv\n        isLeanback\n        isMultidex\n        isSignedV1\n        isSignedV2\n        isSignedV3\n        isValidApk\n        isWearable\n        mainActivity\n        mainActivityList\n        manifestFeatures\n        manifestLibraries\n        manifestXml\n        maxSdkVersion\n        minSdkVersion\n        packagename\n        permissionDetails\n        permissions\n        permissionsDeclared\n        permissionsDeclaredDetails\n        permissionsImplied\n        permissionsRequestedThirdParty\n        providers\n        receivers\n        services\n        signatureNames\n        targetSdkVersion\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": types.AndroguardReportFragmentDoc,
    "\n    fragment ApkidReport on ApkidReportType {\n        id\n        files\n        rulesSha256\n        reportFileJson {\n            data\n        }\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": types.ApkidReportFragmentDoc,
    "\n    fragment ApkleaksReport on ApkleaksReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": types.ApkleaksReportFragmentDoc,
    "\n    fragment ExodusReport on ExodusReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n": types.ExodusReportFragmentDoc,
    "\n    query GetRqJobList {\n        rq_job_list {\n            description\n            funcName\n            id\n            isFailed\n            isFinished\n            queueName\n            startedAt\n            status\n        }\n    }\n": types.GetRqJobListDocument,
    "\n    query GetRqJobQueueNames {\n        rq_queue_name_list\n    }\n": types.GetRqJobQueueNamesDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetApiHealth {\n        isApiUp\n    }\n"): (typeof documents)["\n    query GetApiHealth {\n        isApiUp\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation CreateAppImportJob($queueName: String!, $storageIndex: Int!) {\n        createAppImportJob(\n            queueName: $queueName,\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n"): (typeof documents)["\n    mutation CreateAppImportJob($queueName: String!, $storageIndex: Int!) {\n        createAppImportJob(\n            queueName: $queueName,\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment AppAll on AndroidAppType {\n        absoluteStorePath\n        androidManifestDict\n        fileSizeBytes\n        filename\n        id\n        indexedDate\n        md5\n        originalFilename\n        packagename\n        partitionName\n        pk\n        relativeFirmwarePath\n        relativeStorePath\n        sha1\n        sha256\n        firmwareIdReference {\n            id\n        }\n        firmwareFileReference {\n            id\n        }\n    }\n"): (typeof documents)["\n    fragment AppAll on AndroidAppType {\n        absoluteStorePath\n        androidManifestDict\n        fileSizeBytes\n        filename\n        id\n        indexedDate\n        md5\n        originalFilename\n        packagename\n        partitionName\n        pk\n        relativeFirmwarePath\n        relativeStorePath\n        sha1\n        sha256\n        firmwareIdReference {\n            id\n        }\n        firmwareFileReference {\n            id\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetAppsByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    androidAppIdList {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetAppsByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    androidAppIdList {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetAppById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    androidAppIdList(id: $id) {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetAppById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    androidAppIdList(id: $id) {\n                        edges {\n                            node {\n                                ...AppAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetScannerModuleNames {\n        scanner_module_name_list\n    }\n"): (typeof documents)["\n    query GetScannerModuleNames {\n        scanner_module_name_list\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation ScanApksByObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            objectIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n"): (typeof documents)["\n    mutation ScanApksByObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            objectIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetAuthToken($password: String!, $username: String!) {\n        tokenAuth(password: $password, username: $username) {\n            payload\n        }\n    }\n"): (typeof documents)["\n    query GetAuthToken($password: String!, $username: String!) {\n        tokenAuth(password: $password, username: $username) {\n            payload\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation DeleteTokenCookie {\n        deleteTokenCookie {\n            deleted\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteTokenCookie {\n        deleteTokenCookie {\n            deleted\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetCurrentUserId {\n        me {\n            id\n        }\n    }\n"): (typeof documents)["\n    query GetCurrentUserId {\n        me {\n            id\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetCurrentUserEmailAndUsername {\n        me {\n            email\n            username\n        }\n    }\n"): (typeof documents)["\n    query GetCurrentUserEmailAndUsername {\n        me {\n            email\n            username\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment FileAll on FirmwareFileType {\n        id\n        name\n        absoluteStorePath\n        fileSizeBytes\n        indexedDate\n        isDirectory\n        isOnDisk\n        isSymlink\n        md5\n        metaDict\n        parentDir\n        partitionName\n        relativePath\n        firmwareIdReference {\n            id\n        }\n        androidAppReference {\n            id\n        }\n    }\n"): (typeof documents)["\n    fragment FileAll on FirmwareFileType {\n        id\n        name\n        absoluteStorePath\n        fileSizeBytes\n        indexedDate\n        isDirectory\n        isOnDisk\n        isSymlink\n        md5\n        metaDict\n        parentDir\n        partitionName\n        relativePath\n        firmwareIdReference {\n            id\n        }\n        androidAppReference {\n            id\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetFilesByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    firmwareFileIdList {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetFilesByFirmwareObjectIds($objectIds: [String!]) {\n        android_firmware_connection(objectIdList: $objectIds) {\n            edges {\n                node {\n                    firmwareFileIdList {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetFileById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    firmwareFileIdList(id: $id) {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetFileById($id: ID!) {\n        android_firmware_connection {\n            edges {\n                node {\n                    firmwareFileIdList(id: $id) {\n                        edges {\n                            node {\n                                ...FileAll\n                            }\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation CreateFirmwareExtractorJob($queueName: String!, $storageIndex: Int!) {\n        createFirmwareExtractorJob(\n            createFuzzyHashes: false\n            queueName: $queueName\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n"): (typeof documents)["\n    mutation CreateFirmwareExtractorJob($queueName: String!, $storageIndex: Int!) {\n        createFirmwareExtractorJob(\n            createFuzzyHashes: false\n            queueName: $queueName\n            storageIndex: $storageIndex\n        ) {\n            jobId\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment FirmwareAll on AndroidFirmwareType {\n        absoluteStorePath\n        aecsBuildFilePath\n        fileSizeBytes\n        filename\n        hasFileIndex\n        hasFuzzyHashIndex\n        id\n        indexedDate\n        md5\n        originalFilename\n        osVendor\n        partitionInfoDict\n        pk\n        relativeStorePath\n        sha1\n        sha256\n        tag\n        versionDetected\n    }\n"): (typeof documents)["\n    fragment FirmwareAll on AndroidFirmwareType {\n        absoluteStorePath\n        aecsBuildFilePath\n        fileSizeBytes\n        filename\n        hasFileIndex\n        hasFuzzyHashIndex\n        id\n        indexedDate\n        md5\n        originalFilename\n        osVendor\n        partitionInfoDict\n        pk\n        relativeStorePath\n        sha1\n        sha256\n        tag\n        versionDetected\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetFirmwaresByObjectIds(\n        $objectIds: [String!]\n        $first: Int\n        $after: String\n    ) {\n        android_firmware_connection(\n            objectIdList: $objectIds\n            first: $first\n            after: $after\n        ) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareAll\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetFirmwaresByObjectIds(\n        $objectIds: [String!]\n        $first: Int\n        $after: String\n    ) {\n        android_firmware_connection(\n            objectIdList: $objectIds\n            first: $first\n            after: $after\n        ) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareAll\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment FirmwareRowImporterPage on AndroidFirmwareType {\n        id\n        indexedDate\n        originalFilename\n        osVendor\n        versionDetected\n    }\n"): (typeof documents)["\n    fragment FirmwareRowImporterPage on AndroidFirmwareType {\n        id\n        indexedDate\n        originalFilename\n        osVendor\n        versionDetected\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetFirmwaresImporterPage($first: Int, $after: String) {\n        android_firmware_connection(first: $first, after: $after) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareRowImporterPage\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetFirmwaresImporterPage($first: Int, $after: String) {\n        android_firmware_connection(first: $first, after: $after) {\n            edges {\n                cursor\n                node {\n                    ...FirmwareRowImporterPage\n                }\n            }\n            pageInfo {\n                hasNextPage\n                hasPreviousPage\n                startCursor\n                endCursor\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation ScanApksByFirmwareObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            firmwareIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n"): (typeof documents)["\n    mutation ScanApksByFirmwareObjectIds($objectIds: [String!]!, $scannerName: String!, $queueName: String!) {\n        createApkScanJob(\n            firmwareIdList: $objectIds,\n            moduleName: $scannerName,\n            queueName: $queueName,\n        ) {\n            jobIdList\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation DeleteFirmwareByObjectId($objectIds: [String!]!) {\n        deleteAndroidFirmware(firmwareIdList: $objectIds) {\n            jobId\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteFirmwareByObjectId($objectIds: [String!]!) {\n        deleteAndroidFirmware(firmwareIdList: $objectIds) {\n            jobId\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment BasicReportInfo on ApkScannerReportType {\n        id\n        reportDate\n        scannerName\n        scannerVersion\n        androidAppIdReference {\n            id\n            filename\n            firmwareIdReference {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment BasicReportInfo on ApkScannerReportType {\n        id\n        reportDate\n        scannerName\n        scannerVersion\n        androidAppIdReference {\n            id\n            filename\n            firmwareIdReference {\n                id\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetReport($reportObjectId: String, $appObjectId: String, $scannerName: String) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId, android_app_id_reference: $appObjectId, scanner_name: $scannerName}) {\n            ...BasicReportInfo\n        }\n    }\n"): (typeof documents)["\n    query GetReport($reportObjectId: String, $appObjectId: String, $scannerName: String) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId, android_app_id_reference: $appObjectId, scanner_name: $scannerName}) {\n            ...BasicReportInfo\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetScannerReport(\n        $reportObjectId: String\n        $wantAndroguard: Boolean! = false\n        $wantApkid: Boolean! = false\n        $wantApkleaks: Boolean! = false\n        $wantExodus: Boolean! = false\n    ) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId}) {\n            androidAppIdReference {\n                id\n                filename\n                firmwareIdReference {\n                    id\n                }\n                \n                androguardReport: androguardReportReference @include(if: $wantAndroguard) {\n                    ...AndroguardReport\n                }\n                apkidReport: apkidReportReference @include(if: $wantApkid) {\n                    ...ApkidReport\n                }\n                apkleaksReport: apkleaksReportReference @include(if: $wantApkleaks) {\n                    ...ApkleaksReport\n                }\n                exodusReport: exodusReportReference @include(if: $wantExodus) {\n                    ...ExodusReport\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetScannerReport(\n        $reportObjectId: String\n        $wantAndroguard: Boolean! = false\n        $wantApkid: Boolean! = false\n        $wantApkleaks: Boolean! = false\n        $wantExodus: Boolean! = false\n    ) {\n        apk_scanner_report_list(fieldFilter: {id: $reportObjectId}) {\n            androidAppIdReference {\n                id\n                filename\n                firmwareIdReference {\n                    id\n                }\n                \n                androguardReport: androguardReportReference @include(if: $wantAndroguard) {\n                    ...AndroguardReport\n                }\n                apkidReport: apkidReportReference @include(if: $wantApkid) {\n                    ...ApkidReport\n                }\n                apkleaksReport: apkleaksReportReference @include(if: $wantApkleaks) {\n                    ...ApkleaksReport\n                }\n                exodusReport: exodusReportReference @include(if: $wantExodus) {\n                    ...ExodusReport\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment AndroguardReport on AndroGuardReportType {\n        id\n        activities\n        androidVersionCode\n        androidVersionName\n        appName\n        dexNames\n        effectiveTargetVersion\n        fileNameList\n        intentFiltersDict\n        isAndroidtv\n        isLeanback\n        isMultidex\n        isSignedV1\n        isSignedV2\n        isSignedV3\n        isValidApk\n        isWearable\n        mainActivity\n        mainActivityList\n        manifestFeatures\n        manifestLibraries\n        manifestXml\n        maxSdkVersion\n        minSdkVersion\n        packagename\n        permissionDetails\n        permissions\n        permissionsDeclared\n        permissionsDeclaredDetails\n        permissionsImplied\n        permissionsRequestedThirdParty\n        providers\n        receivers\n        services\n        signatureNames\n        targetSdkVersion\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"): (typeof documents)["\n    fragment AndroguardReport on AndroGuardReportType {\n        id\n        activities\n        androidVersionCode\n        androidVersionName\n        appName\n        dexNames\n        effectiveTargetVersion\n        fileNameList\n        intentFiltersDict\n        isAndroidtv\n        isLeanback\n        isMultidex\n        isSignedV1\n        isSignedV2\n        isSignedV3\n        isValidApk\n        isWearable\n        mainActivity\n        mainActivityList\n        manifestFeatures\n        manifestLibraries\n        manifestXml\n        maxSdkVersion\n        minSdkVersion\n        packagename\n        permissionDetails\n        permissions\n        permissionsDeclared\n        permissionsDeclaredDetails\n        permissionsImplied\n        permissionsRequestedThirdParty\n        providers\n        receivers\n        services\n        signatureNames\n        targetSdkVersion\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ApkidReport on ApkidReportType {\n        id\n        files\n        rulesSha256\n        reportFileJson {\n            data\n        }\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"): (typeof documents)["\n    fragment ApkidReport on ApkidReportType {\n        id\n        files\n        rulesSha256\n        reportFileJson {\n            data\n        }\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ApkleaksReport on ApkleaksReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"): (typeof documents)["\n    fragment ApkleaksReport on ApkleaksReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ExodusReport on ExodusReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"): (typeof documents)["\n    fragment ExodusReport on ExodusReportType {\n        id\n        results\n        reportDate\n        scannerName\n        scannerVersion\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetRqJobList {\n        rq_job_list {\n            description\n            funcName\n            id\n            isFailed\n            isFinished\n            queueName\n            startedAt\n            status\n        }\n    }\n"): (typeof documents)["\n    query GetRqJobList {\n        rq_job_list {\n            description\n            funcName\n            id\n            isFailed\n            isFinished\n            queueName\n            startedAt\n            status\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query GetRqJobQueueNames {\n        rq_queue_name_list\n    }\n"): (typeof documents)["\n    query GetRqJobQueueNames {\n        rq_queue_name_list\n    }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;